# Generated by Django 6.0.1 on 2026-01-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_options_alter_borrow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='borrow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
